POST http://localhost:8000/
Content-Type: application/json

{
    "username":"julian@gonzalez.com",
    "password":"123456"
}
###
GET http://localhost:8000/vehiculos
Content-Type: application/json
Authorization: Julian eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJqdWxpYW5AZ29uemFsZXouY29tIiwiZXhwIjoxNzQxOTA4MDM5fQ.D6GDY-IT-dT3tCJDiZJpYxI2h4ySbRGCJP07KUoHego

###
GET http://localhost:8000/usuarios
Content-Type: application/json
Authorization: Julian eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJqdWxpYW5AZ29uemFsZXouY29tIiwiZXhwIjoxNzQxOTA4MDM5fQ.D6GDY-IT-dT3tCJDiZJpYxI2h4ySbRGCJP07KUoHego