POST http://localhost:8000/
Content-Type: application/json

{
    "username":"julian@gonzalez.com",
    "password":"123456"
}
###
GET http://localhost:8000/usuarios

###
GET http://localhost:8000/usuarios
Content-Type: application/json
Authorization: Julian eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJqdWxpYW5AZ29uemFsZXouY29tIiwiZXhwIjoxNzQxODk0NzAwfQ.J7hb6nhCiiSOhe4t_6mG0ePt9Ok7uD5fl0IbUW3V9zw